@startuml ApocalipsisZombie

interface RMIInterfaz {
  + finalizar(): void
  + getNumeroHumanosEsperaIda(i: int): int
  + getNumeroHumanosEsperaVuelta(i: int): int
  + getIniciado(): boolean
  + getMejoresZombies(): String
  + getNumeroHumanosRefugio(): int
  + getNumeroHumanosTunel(tunel: int): int
  + getNumeroHumanosZonaRiesgo(zona: int): int
  + getNumeroZombiesZonaRiesgo(zona: int): int
  + setParado(parado: boolean): void
}

class RetornaValores {
  - mapa: Mapa
  + RetornaValores(mapa: Mapa)
  + finalizar(): void
  + getNumeroHumanosEsperaIda(i: int): int
  + getNumeroHumanosEsperaVuelta(i: int): int
  + getIniciado(): boolean
  + getMejoresZombies(): String
  + getNumeroHumanosRefugio(): int
  + getNumeroHumanosTunel(tunel: int): int
  + getNumeroHumanosZonaRiesgo(zona: int): int
  + getNumeroZombiesZonaRiesgo(zona: int): int
  + setParado(parado: boolean): void
}

class Mapa {
  - zonaRefugio: ZonaRefugio
  - zonaRiesgo: ZonaRiesgo
  - zonaTuneles: ZonaTuneles
  - pausado: boolean
  - iniciado: boolean
  - quierenVolver: AtomicInteger[]
  - cb_tuneles: CyclicBarrier[]
  - puedeEntrarIda: Semaphore[]
  - puedeEntrarVuelta: Semaphore[]
  - ticketPasarTunel: Semaphore[]
  - lockZonaRiesgo: Lock[]
  - lockZonaDescanso: Lock
  - lockZonaComedor: Lock
  - lockZonaComun: Lock
  - locks_tuneles: Lock[]
  - esperarComida: Condition
  + Mapa()
  + pasarTunelIda(tunelElegido: int, humano: Humano)
  + pasarTunelVuelta(tunelElegido: int, humano: Humano)
  + entrarZonaDescanso(humano: Humano)
  + salirZonaDescanso(humano: Humano)
  + entrarZonaRiesgo(tunelTomado: int, humano: Humano)
  + entrarZonaComedor(humano: Humano)
  + salirZonaComedor(humano: Humano)
  + entrarZonaComun(humano: Humano)
  + cambiarDeZona(zonaInicial: int, zombie: Zombie): int
  + atacar(zombie: Zombie, zonaZombie: int)
  + verificarPausa()
  + pausarHilos()
  + reanudarHilos()
  + finalizar()
}

class ZonaRefugio {
  - zonaComun: List<Humano>
  - zonaDescanso: List<Humano>
  - zonaComedor: List<Humano>
  - almacen_comida: int
  + getNumeroHumanos(): int
  + addComida(cantidad: int)
  + takeComida()
}

class ZonaRiesgo {
  - zonas: List<Thread>[]
}

class ZonaTuneles {
  - tuneles: List<Humano>[]
  - zonasEsperaIda: List<Humano>[]
  - zonasEsperaVuelta: List<Humano>[]
}

class Humano {
  - id: String
  - comida: int
  - marcado: boolean
  - siendoAtacado: boolean
  - muerte: boolean
  - mapa: Mapa
  + Humano(mapa: Mapa, id: String)
  + run()
  + getIde(): String
  + getComida(): int
  + setComida(comida: int)
  + marcarHumano()
  + getSiendoAtacado(): boolean
  + setSiendoAtacado(siendoAtacado: boolean)
  + dormir(milis: int)
  + morir(muerto: boolean)
}

class Zombie {
  - id: String
  - zonaInicial: int
  - mapa: Mapa
  - kills: int
  + Zombie(id: String, mapa: Mapa, zonaInicial: int)
  + run()
  + getIde(): String
  + sumarKills()
  + getNumeroKills(): int
  + dormir(milis: int)
}

' Relaciones
RetornaValores ..|> RMIInterfaz
RetornaValores --> Mapa

Mapa "1" *-- "1" ZonaRefugio
Mapa "1" *-- "1" ZonaRiesgo
Mapa "1" *-- "1" ZonaTuneles

Humano --> Mapa
Zombie --> Mapa

' Controladores
class FinJuego {
  - salirButton: Button
  + onSalirButtonClick(actionEvent: ActionEvent)
}

class VistaClienteController {
  - humanosTunelesText0: TextField
  - humanosAreasInsegurasText0: TextField
  - zombisAreasInsegurasText0: TextField
  - parado: boolean
  - retornaValores: RMIInterfaz
  + iniciarActualizacionDeValores()
  + onEjecucionButtonClick(actionEvent: ActionEvent)
  + setRetornaValores(mapa: RMIInterfaz)
}

class VentanaPrincipalController {
  - mapa: Mapa
  - botonIniciar: Button
  - escenaPrincipal: Stage
  + setStage(stage: Stage)
  + setMapa(mapa: Mapa)
  + botonIniciarClick()
}

class VentanaInicialController {
  - mapa: Mapa
  - iniciarPartidaButton: Button
  + iniciarPartidaButtonClick(actionEvent: ActionEvent)
  + setMapa(mapa: Mapa)
  + onCreditosButtonClick(actionEvent: ActionEvent)
}

class NombreController {
  - mapa: Mapa
  - textFieldNombre: TextField
  - continuarButton: Button
  - VolverButton: Button
  - labelError: Label
  - nombreGuardadoString: String
  + onSiguienteButtonClick(actionEvent: ActionEvent)
  + onVolverButtonClick(actionEvent: ActionEvent)
  + setMapa(mapa: Mapa)
}

class PantallaJuegoController {
  - mapa: Mapa
  - finalizarButton: Button
  - txtTiempo: TextField
  - botonReanudar: Button
  + setData(mapa: Mapa)
  + onBotonReanudar(actionEvent: ActionEvent)
  + recorrerZonaRefugio()
  + recorrerZonaTuneles()
  + recorrerZonaRiesgo()
  + pararTodo()
  + onFinalizarButton(actionEvent: ActionEvent)
}

class CreditosController {
  - VolverButton: Button
  + onVolverButtonClick(actionEvent: ActionEvent)
}

' Relaciones controladores
VistaClienteController --> RMIInterfaz
VentanaPrincipalController --> Mapa
VentanaInicialController --> Mapa
NombreController --> Mapa
PantallaJuegoController --> Mapa

@enduml